
const cfg=window.MONEY_PULSE_CONFIG||{};
const el=id=>document.getElementById(id);
let credential='',deferredInstall=null,privacy=false;
const deviceId=localStorage.getItem('mpDeviceId')||('DEV-'+crypto.randomUUID());localStorage.setItem('mpDeviceId',deviceId);
function configured(){return cfg.GOOGLE_CLIENT_ID&&!cfg.GOOGLE_CLIENT_ID.startsWith('PASTE_')&&cfg.APPS_SCRIPT_API_URL&&!cfg.APPS_SCRIPT_API_URL.startsWith('PASTE_');}
function setStatus(id,text,state){el(id+'Status').textContent=text;el(id+'Dot').className='dot '+(state||'');}
function message(text){el('message').textContent=text;}
async function health(){if(!configured()){setStatus('api','Configuration required','warn');message('Open config.js in GitHub and enter the Web Client ID and Apps Script /exec URL.');return;}try{const r=await fetch(cfg.APPS_SCRIPT_API_URL+'?action=HEALTH_CHECK',{redirect:'follow',cache:'no-store'}),j=await r.json();if(!j.success)throw Error('Health check failed');setStatus('api',j.api+' '+j.version,'ok');message('API connection is ready. Sign in with the authorized Google account.');}catch(e){setStatus('api','Connection failed','bad');message('The API could not be reached. Check config.js and the Apps Script deployment.');}}
function request(action,token){return fetch(cfg.APPS_SCRIPT_API_URL,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({apiVersion:'1',action,requestId:'REQ-'+crypto.randomUUID(),operationId:'OP-'+crypto.randomUUID(),deviceId,timestamp:new Date().toISOString(),identityToken:token,payload:{}})}).then(r=>r.json());}
function initGoogle(){if(!configured()||!window.google?.accounts?.id)return setTimeout(initGoogle,300);google.accounts.id.initialize({client_id:cfg.GOOGLE_CLIENT_ID,callback:onCredential,auto_select:false,cancel_on_tap_outside:false});el('signInBtn').onclick=()=>google.accounts.id.prompt(n=>{if(n.isNotDisplayed()||n.isSkippedMoment())google.accounts.id.renderButton(el('signInBtn'),{theme:'filled_blue',shape:'pill',size:'large',text:'signin_with'});});}
async function onCredential(resp){credential=resp.credential;setStatus('auth','Verifying...','warn');message('Verifying the authorized account...');try{let a=await request('AUTHENTICATE',credential);if(!a.success)throw Error(a.error?.message||'Authentication failed');setStatus('auth','Authorized as '+a.data.displayEmail,'ok');el('signInBtn').textContent='Signed in';el('signInBtn').disabled=true;let s=await request('GET_APP_STATE',credential);if(!s.success)throw Error(s.error?.message||'Database load failed');setStatus('db','Private database connected','ok');el('txCount').textContent=s.data.transactionCount||0;el('categoryCount').textContent=(s.data.categories||[]).length;el('accountCount').textContent=(s.data.accounts||[]).length;message('Secure connection complete. MoneyPulse is ready for the next build stage.');}catch(e){setStatus('auth','Access denied','bad');message(e.message||'Google sign-in could not be verified.');}}
function sync(){el('syncBtn').textContent='⟳';health().finally(()=>setTimeout(()=>el('syncBtn').innerHTML='↻<span id="syncTip" class="tooltip">Check connection</span>',500));}
function togglePrivacy(){privacy=!privacy;document.body.classList.toggle('privacy',privacy);el('privacyBtn').innerHTML=(privacy?'⊘':'◉')+'<span id="privacyTip" class="tooltip">'+(privacy?'Show values':'Hide values')+'</span>';el('privacyBtn').setAttribute('aria-label',privacy?'Show values':'Hide values');}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;el('installBtn').classList.remove('hidden');});
el('installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;el('installBtn').classList.add('hidden');};
el('syncBtn').onclick=sync;el('privacyBtn').onclick=togglePrivacy;
document.querySelectorAll('.nav-icon[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-icon').forEach(x=>x.classList.remove('active'));b.classList.add('active');el('pageTitle').textContent=b.dataset.page;});
window.addEventListener('online',()=>{setStatus('api','Back online','warn');health();});window.addEventListener('offline',()=>{setStatus('api','Offline','warn');message('MoneyPulse is offline. The installed app shell remains available.');});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
window.addEventListener('load',()=>{setTimeout(()=>{el('splash').classList.add('hidden');el('app').classList.remove('hidden');health();initGoogle();},850);});
